### ISSUE TITLE
Error after activating

### ISSUE THREAD

**Issue by ldevigne** [shifthappens/hxeventmanager#3]
Hi, I have this error after activating hx plugin :

Fatal error: Uncaught Error: Call to undefined function mysql_real_escape_string() in /usr/src/wordpress/wp-content/plugins/hxeventmanager-master/classes/custombookingsfieldstable.class.php:64 Stack trace: #0 /usr/src/wordpress/wp-content/plugins/hxeventmanager-master/views/form_editor.php(6): CustomBookingsFieldsTable->prepare_items() #1 /usr/src/wordpress/wp-content/plugins/hxeventmanager-master/custombooking.php(550): include('/usr/src/wordpr...') #2 /usr/src/wordpress/wp-includes/class-wp-hook.php(286): CustomBookingsFormEditor::form_editor_overview('') #3 /usr/src/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #4 /usr/src/wordpress/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /usr/src/wordpress/wp-admin/admin.php(224): do_action('event_page_even...') #6 /usr/src/wordpress/wp-admin/edit.php(10): require_once('/usr/src/wordpr...') #7 {main} thrown in /usr/src/wordpress/wp-content/plugins/hxeventmanager-master/classes/custombookingsfieldstable.class.php on line 64

**Comment by ldevigne** [comment]
Saw that it's depecrated since php 5.3
my php version is "7.2.1"
https://stackoverflow.com/questions/13856639/mysql-real-escape-string-is-undefined

**Comment by ldevigne** [comment]
So I replaced those lines with mysqli and got :
"Warning: mysqli_real_escape_string() expects exactly 2 parameters, 1 given in /usr/src/wordpress/wp-content/plugins/hxeventmanager-master/classes/custombookingsfieldstable.class.php on line 64"

That's why I think he can't find existing fields of my form..
![2018_10_08_11_13_27_ldevigne_scw_2e67f3_](https://user-images.githubusercontent.com/7534383/46600698-4c3d2100-caeb-11e8-8c8a-91528d83c4f2.png)
